trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '<Your Azure Service Connection>'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '<Your Resource Group Name>'
    location: '<Your Azure Region>'
    templateLocation: 'Linked artifact'
    csmFile: 'path/to/your/azuredeploy.json'
    overrideParameters: '-adminUsername $(vmAdminUsername) -adminPassword $(vmAdminPassword)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: Ansible@4
  inputs:
    playbookPath: 'path/to/your/deploy.yml'
    inventoryFile: 'path/to/your/inventory'
    extraVars: 'page_title="My Landing Page" page_description="This is my landing page description"'
    become: true
