---
- hosts: all
  become: yes
  vars:
    page_title: "My Landing Page"
    page_description: "This is my landing page description."
  tasks:
    - name: Install EPEL repository on CentOS
      command: sudo yum install -y epel-release

    - name: Update YUM package cache
      yum:
        name: '*'
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Create destination directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Apply Page Template
      template:
        src: files/landing-page.html.j2
        dest: /var/www/html/index.html

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Allow all access to tcp port 80
      firewalld:
        port: '80/tcp'
        permanent: true
        state: enabled
      become: true
