trigger:
- main

jobs:
- job: deploy_vm
  displayName: 'Deploy Linux VM'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      version: '3.x'
      performMultiLevelLookup: true

  - task: UseNode@2
    displayName: 'Use Node.js'
    inputs:
      version: '16.x'

  - task: InstallAnsible@1
    displayName: 'Install Ansible'
    inputs:
      versionSpec: '2.9.x'

  - script: 'ansible-playbook create_vm.yml'
    displayName: 'Run Ansible Playbook'
    env:
      AZURE_CLIENT_ID: 769cabdb-a4d5-4199-a760-b72ca471f16d
      AZURE_SECRET: E~w8Q~NQCn12IR0e_.hCtaV2fNI9quwW8oT5maks
      AZURE_SUBSCRIPTION_ID: e9a82d9b-fa70-49d3-a021-f33cad90e629
      AZURE_TENANT: 938cd77c-7886-4bb2-bab2-9726d7cff02e
