---
- name: Create Azure Resource Group, Network, VM, and SSH
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    resource_group: test_rg
    location: East US
    vnet_name: test_vnet
    subnet_name: test_subnet
    vm_name: test_vm
    admin_username: azureUser
    ssh_private_key_path: ./private-key.pem
    image_publisher: Canonical
    image_offer: UbuntuServer
    image_sku: 18.04-LTS
    vm_size: Standard_B1s

  tasks:
    - name: Create Azure Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
      delegate_to: localhost

    - name: Create Azure Virtual Network
      azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        address_prefixes: "{{ vnet_address_prefix }}"
        subnets:
          - name: "{{ subnet_name }}"
            address_prefix: "{{ subnet_address_prefix }}"
      delegate_to: localhost

    - name: Create Azure VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        ssh_key_data: "{{ lookup('file', ssh_private_key_path) }}"
        image:
          offer: "{{ image_offer }}"
          publisher: "{{ image_publisher }}"
          sku: "{{ image_sku }}"
        location: "{{ location }}"
        os_disk_caching: ReadWrite
        network_interface_names:
          - "{{ vm_name }}-nic"
        assign_identity: no
        unmanaged_disk_vhd_uri: null
      delegate_to: localhost

    - name: Get public IP address
      azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}-pip"
      register: public_ip_info

    - name: Display public IP information
      debug:
        var: public_ip_info.resources[0].ipAddress
